WARNING:tensorflow:From /home/aogorodnikov/anaconda3/envs/imgSudoku/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-09-04 08:02:42.120791: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-09-04 08:02:42.129243: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300075000 Hz
2019-09-04 08:02:42.130098: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x562422b327e0 executing computations on platform Host. Devices:
2019-09-04 08:02:42.130133: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Autoencoder Architecture
Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         (None, 144, 144, 3)       0         
_________________________________________________________________
sequential_1 (Sequential)    (None, 32)                80860640  
_________________________________________________________________
sequential_2 (Sequential)    (None, 144, 144, 3)       80829091  
=================================================================
Total params: 161,689,731
Trainable params: 161,668,803
Non-trainable params: 20,928
_________________________________________________________________
None
Discriminator Architecture
Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
dense_7 (Dense)              (None, 5184)              171072    
_________________________________________________________________
dense_8 (Dense)              (None, 5184)              26879040  
_________________________________________________________________
dense_9 (Dense)              (None, 1)                 5185      
=================================================================
/home/aogorodnikov/anaconda3/envs/imgSudoku/lib/python3.7/site-packages/keras/engine/training.py:493: UserWarning: Discrepancy between trainable weights and collected trainable weights, did you set `model.trainable` without calling `model.compile` after ?
  'Discrepancy between trainable weights and collected trainable'
Total params: 54,110,594
Trainable params: 27,055,297
Non-trainable params: 27,055,297
_________________________________________________________________
None
Generator Architecture
Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_2 (InputLayer)         (None, 144, 144, 3)       0         
_________________________________________________________________
sequential_1 (Sequential)    (None, 32)                80860640  
_________________________________________________________________
sequential_3 (Sequential)    (None, 1)                 27055297  
=================================================================
Total params: 107,915,937
Trainable params: 80,839,712
Non-trainable params: 27,076,225
_________________________________________________________________
None
Found 1083 images belonging to 1 classes.
WARNING:tensorflow:From /home/aogorodnikov/anaconda3/envs/imgSudoku/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/1
/home/aogorodnikov/anaconda3/envs/imgSudoku/lib/python3.7/site-packages/keras_preprocessing/image/image_data_generator.py:716: UserWarning: This ImageDataGenerator specifies `featurewise_center`, but it hasn't been fit on any training data. Fit it first by calling `.fit(numpy_data)`.
  warnings.warn('This ImageDataGenerator specifies '
/home/aogorodnikov/anaconda3/envs/imgSudoku/lib/python3.7/site-packages/keras_preprocessing/image/image_data_generator.py:724: UserWarning: This ImageDataGenerator specifies `featurewise_std_normalization`, but it hasn't been fit on any training data. Fit it first by calling `.fit(numpy_data)`.
  warnings.warn('This ImageDataGenerator specifies '
 1/34 [..............................] - ETA: 8:14 - loss: 883.7322 - acc: 0.2324 2/34 [>.............................] - ETA: 4:52 - loss: 971.0956 - acc: 0.2453 3/34 [=>............................] - ETA: 3:44 - loss: 998.1610 - acc: 0.2648 4/34 [==>...........................] - ETA: 3:04 - loss: 991.4013 - acc: 0.2799 5/34 [===>..........................] - ETA: 2:41 - loss: 988.2406 - acc: 0.2817 6/34 [====>.........................] - ETA: 2:26 - loss: 958.4913 - acc: 0.3019