WARNING:tensorflow:From /home/aogorodnikov/anaconda3/envs/imgSudoku/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-09-14 01:54:18.435345: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-09-14 01:54:18.442548: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300035000 Hz
2019-09-14 01:54:18.443308: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x561459f24010 executing computations on platform Host. Devices:
2019-09-14 01:54:18.443337: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Autoencoder Architecture
Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         (None, 104, 104, 3)       0         
_________________________________________________________________
sequential_1 (Sequential)    (None, 32)                22069760  
_________________________________________________________________
sequential_2 (Sequential)    (None, 104, 104, 3)       22053091  
=================================================================
Total params: 44,122,851
Trainable params: 44,111,843
Non-trainable params: 11,008
_________________________________________________________________
None
Discriminator Architecture
Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
dense_7 (Dense)              (None, 2704)              89232     
_________________________________________________________________
dense_8 (Dense)              (None, 2704)              7314320   
_________________________________________________________________
dense_9 (Dense)              (None, 1)                 2705      
=================================================================
/home/aogorodnikov/anaconda3/envs/imgSudoku/lib/python3.7/site-packages/keras/engine/training.py:493: UserWarning: Discrepancy between trainable weights and collected trainable weights, did you set `model.trainable` without calling `model.compile` after ?
  'Discrepancy between trainable weights and collected trainable'
Total params: 14,812,514
Trainable params: 7,406,257
Non-trainable params: 7,406,257
_________________________________________________________________
None
Generator Architecture
Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_2 (InputLayer)         (None, 104, 104, 3)       0         
_________________________________________________________________
sequential_1 (Sequential)    (None, 32)                22069760  
_________________________________________________________________
sequential_3 (Sequential)    (None, 1)                 7406257   
=================================================================
Total params: 29,476,017
Trainable params: 22,058,752
Non-trainable params: 7,417,265
_________________________________________________________________
None
Found 1083 images belonging to 1 classes.
WARNING:tensorflow:From /home/aogorodnikov/anaconda3/envs/imgSudoku/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/1
/home/aogorodnikov/anaconda3/envs/imgSudoku/lib/python3.7/site-packages/keras_preprocessing/image/image_data_generator.py:716: UserWarning: This ImageDataGenerator specifies `featurewise_center`, but it hasn't been fit on any training data. Fit it first by calling `.fit(numpy_data)`.
  warnings.warn('This ImageDataGenerator specifies '
/home/aogorodnikov/anaconda3/envs/imgSudoku/lib/python3.7/site-packages/keras_preprocessing/image/image_data_generator.py:724: UserWarning: This ImageDataGenerator specifies `featurewise_std_normalization`, but it hasn't been fit on any training data. Fit it first by calling `.fit(numpy_data)`.
  warnings.warn('This ImageDataGenerator specifies '
 1/17 [>.............................] - ETA: 1:34 - loss: 0.1716 - acc: 0.1222 2/17 [==>...........................] - ETA: 54s - loss: 0.1709 - acc: 0.1114  3/17 [====>.........................] - ETA: 40s - loss: 0.1705 - acc: 0.1034 4/17 [======>.......................] - ETA: 32s - loss: 0.1688 - acc: 0.1028 5/17 [=======>......................] - ETA: 27s - loss: 0.1676 - acc: 0.0987 6/17 [=========>....................] - ETA: 23s - loss: 0.1662 - acc: 0.0945 7/17 [===========>..................] - ETA: 20s - loss: 0.1640 - acc: 0.0919 8/17 [=============>................] - ETA: 17s - loss: 0.1611 - acc: 0.0904 9/17 [==============>...............] - ETA: 15s - loss: 0.1571 - acc: 0.092010/17 [================>.............] - ETA: 12s - loss: 0.1523 - acc: 0.091311/17 [==================>...........] - ETA: 10s - loss: 0.1471 - acc: 0.090212/17 [====================>.........] - ETA: 8s - loss: 0.1420 - acc: 0.0908 13/17 [=====================>........] - ETA: 6s - loss: 0.1365 - acc: 0.091114/17 [=======================>......] - ETA: 5s - loss: 0.1307 - acc: 0.091215/17 [=========================>....] - ETA: 3s - loss: 0.1249 - acc: 0.091716/17 [===========================>..] - ETA: 1s - loss: 0.1191 - acc: 0.091917/17 [==============================] - 28s 2s/step - loss: 0.1135 - acc: 0.0920
!!!DEBUG
[]
discriminator_loss = 0.3353939770775683

EPOCH 1 DONE
Epoch 1/1
 1/17 [>.............................] - ETA: 31s - loss: 0.0243 - acc: 0.0881 2/17 [==>...........................] - ETA: 27s - loss: 0.0216 - acc: 0.0870 3/17 [====>.........................] - ETA: 25s - loss: 0.0197 - acc: 0.0900 4/17 [======>.......................] - ETA: 22s - loss: 0.0185 - acc: 0.0936 5/17 [=======>......................] - ETA: 20s - loss: 0.0178 - acc: 0.0975 6/17 [=========>....................] - ETA: 17s - loss: 0.0173 - acc: 0.1048 7/17 [===========>..................] - ETA: 15s - loss: 0.0169 - acc: 0.1148 8/17 [=============>................] - ETA: 13s - loss: 0.0166 - acc: 0.1290 9/17 [==============>...............] - ETA: 12s - loss: 0.0162 - acc: 0.145810/17 [================>.............] - ETA: 10s - loss: 0.0159 - acc: 0.163811/17 [==================>...........] - ETA: 8s - loss: 0.0157 - acc: 0.1852 12/17 [====================>.........] - ETA: 7s - loss: 0.0155 - acc: 0.206313/17 [=====================>........] - ETA: 5s - loss: 0.0154 - acc: 0.224514/17 [=======================>......] - ETA: 4s - loss: 0.0151 - acc: 0.242915/17 [=========================>....] - ETA: 2s - loss: 0.0150 - acc: 0.262516/17 [===========================>..] - ETA: 1s - loss: 0.0148 - acc: 0.275917/17 [==============================] - 25s 1s/step - loss: 0.0146 - acc: 0.2917
!!!DEBUG
[]
Traceback (most recent call last):
  File "aae.py", line 411, in <module>
    adversarial=argsP.adversarial
  File "aae.py", line 236, in train
    discriminator_losses[epoch-1]
IndexError: list index out of range
